on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - main

jobs:
  one:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'enhancement'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
