on:
  push:
    branches:
     - test
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch init event
        if: github.event.action != 'release'
        run: |
          curl -X POST https://api.github.com/repos/adroaldoneto/gha-dispatch-event/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "release", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "ref_name": "${{ github.ref_name }}" }}'
