name: Verify Workflow

on: 
  repository_dispatch:
    type: [verify-workflow]

jobs:
  VERIFY_WORKFLOW:
    runs-on: ubuntu-latest
    steps:

      - name: Callback
        if: github.event.client_payload.state == 'pending'
        # set the merge commit status check
        # using GitHub REST API
        # see https://docs.github.com/en/rest/reference/repos#create-a-commit-status
        run: |
          curl --request POST \
          --url ${{ github.event.client_payload.statuses_href }} \
          -u '${{ secrets.ACCESS_TOKEN }}' \
          --header 'content-type: application/vnd.github+json' \
          --data '{
            "context": "Check Callback",
            "state": "pending",
            "description": "pending",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: Callback ✅
        if: github.event.client_payload.state == 'success'
        # set the merge commit status check
        # using GitHub REST API
        # see https://docs.github.com/en/rest/reference/repos#create-a-commit-status
        run: |
          curl --request POST \
          --url ${{ github.event.client_payload.statuses_href }} \
          -u '${{ secrets.ACCESS_TOKEN }}' \
          --header 'content-type: application/vnd.github+json' \
          --data '{
            "context": "Check Callback",
            "state": "success",
            "description": "passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: Callback 🚨
        if: github.event.client_payload.state == 'failure'
        # set the merge commit status check
        # using GitHub REST API
        # see https://docs.github.com/en/rest/reference/repos#create-a-commit-status
        run: |
          curl --request POST \
          --url ${{ github.event.client_payload.statuses_href }} \
          -u '${{ secrets.ACCESS_TOKEN }}' \
          --header 'content-type: application/vnd.github+json' \
          --data '{
            "context": Check Callback",
            "state": "failure",
            "description": "failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      
      - name: Callback 🚨
        if: ${{ failure() }}
          # set the merge commit status check
          # using GitHub REST API
          # see https://docs.github.com/en/rest/reference/repos#create-a-commit-status
          run: |
            curl --request POST \
            --url ${{ github.event.client_payload.statuses_href }} \
            -u '${{ secrets.ACCESS_TOKEN }}' \
            --header 'content-type: application/vnd.github+json' \
            --data '{
              "context": Check Callback",
              "state": "error",
              "description": "Error",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }'
      
