name: Dispatch Event

on:
  pull_request:
    branches:
     - release-*
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      job_id: ${{ steps.build.outputs.job_id }}
    steps:
      - name: Dispatch event
        id: build
        run: |
          curl -X POST https://api.github.com/repos/adroaldoneto/gha-dispatch-event/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "release", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "ref_name": "${{ github.ref_name }}" }}'

  # VERIFY_SAST:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Verify SAST
  #       uses: ./.github/actions/verify
  #       with:
  #         JOB_NAME: build-${{ needs.build.outputs.job_id }}
  #         MINUTES_AGO: 3
  #         DELAY: 17s
  #         WORKFLOW_NAME: gha-dispatch-event
  #         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        
