name: Verify Workflow

on: 
  repository_dispatch:
    type: [security, release, tag]

jobs:
  VERIFY_WORKFLOW:
    runs-on: ubuntu-latest
    steps:

      - name: Check Event Type - ${{ github.event.client_payload.state }}
        id: check_event_type
        if: |
          !contains(fromJson('["pending", "success", "failure"]'), github.event.client_payload.state)
        run: |
          echo "Invalid event typed"
          exit 1

      - name: Callback - ${{ github.event.client_payload.state }}
        run: |
          curl --request POST \
          --url ${{ github.event.client_payload.statuses_href }} \
          -u '${{ secrets.ACCESS_TOKEN }}' \
          --header 'content-type: application/vnd.github+json' \
          -o result.json \
          --data '{
            "context": "${{ github.event.action }} - Check Callback",
            "state": "${{ github.event.client_payload.state }}",
            "description": "${{ github.event.action }} ${{ github.event.client_payload.description }}",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
          
      
      - name: Intenal error ❌
        if: |
          failure() && 
          github.event.client_payload.state != 'failure' &&
          steps.check_event_type.outcome == 'skipped'
        run: |
          curl --request POST \
          --url ${{ github.event.client_payload.statuses_href }} \
          -u '${{ secrets.ACCESS_TOKEN }}' \
          --header 'content-type: application/vnd.github+json' \
          -o error.json \
          --data '{
            "context": "${{ github.event.action }} - Check Callback",
            "state": "error",
            "description": "Internal error",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
  
  publish:
    runs-on: ubuntu-latest
    needs:
      - VERIFY_WORKFLOW
    if: ${{ needs.VERIFY_WORKFLOW.result == 'success' && github.event.action == 'release' }}
    steps:
      - name: Callback - ${{ github.event.client_payload.state }}
        run: |
          echo ${{ github.event.event_type }}
          echo "teste com sucesso"
      
