name: Verify Workflow

on: 
  repository_dispatch:
    type: [security, release, tag]

jobs:
  VERIFY_WORKFLOW:
    runs-on: ubuntu-latest
    steps:

      - name: Callback - ${{ github.event.client_payload.state }}
        if: contains(fromJson('["pending", "success", "failure"]'), github.event.client_payload.state)
        run: |
          curl --request POST \
          --url ${{ github.event.client_payload.statuses_href }} \
          -u '${{ secrets.ACCESS_TOKEN }}' \
          --header 'content-type: application/vnd.github+json' \
          --data '{
            "context": "${{ github.event.action }} - Check Callback",
            "state": "${{ github.event.client_payload.state }}",
            "description": "${{ github.event.action }} ${{ github.event.client_payload.description }}",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
          -o result.json
      
      - name: Interal error ❌
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url ${{ github.event.client_payload.statuses_href }} \
          -u '${{ secrets.ACCESS_TOKEN }}' \
          --header 'content-type: application/vnd.github+json' \
          --data '{
            "context": "${{ github.event.action }} - Check Callback",
            "state": "error",
            "description": "Internal error",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
          -o error.json
      
