# GitHub Actions Workflow created for handling the release process based on the draft release prepared
# with the Build workflow. Running the publishPlugin task requires the PUBLISH_TOKEN secret provided.

name: Release
on:
  release:
    types: [prereleased, released]

jobs:

  # Prepare and publish the plugin to the Marketplace repository
  PUBLISH:
    name: Publish Plugin
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      # # Setup Java 11 environment for the next steps
      # - name: Setup Java
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: zulu
      #     java-version: 11


      # Upload artifact as a release asset
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
        ./gredlew buildPlugin
        gh release upload ${{ github.event.release.tag_name }} ./build/distributions/*

  EXPORT_PROPERTIES:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.properties.output.changelog }}
    steps:    
        # Set environment variables
      - name: Export Properties
        id: properties
        shell: bash
        run: |
          CHANGELOG="$(cat << 'EOM' | sed -e "/## What's Changed/d" -e 's/^[[:space:]]*$//g' -e '/./,$!d'
          ${{ github.event.release.body }}
          EOM
          )"
          
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          CHANGELOG="${CHANGELOG//$'**Full Changelog**'/'Full Changelog'}"

          echo "::set-output name=changelog::$CHANGELOG"

  CHANGELOG:
    needs: 
      - EXPORT_PROPERTIES
    runs-on: ubuntu-latest
    steps:
    # Update Unreleased section with the current release note
      - name: Patch Changelog
        if: ${{ needs.EXPORT_PROPERTIES.outputs.changelog != '' }}
        env:
          CHANGELOG: ${{ steps.properties.outputs.changelog }}
        run: |
          ./gradlew patchChangelog --release-note="$CHANGELOG"

      # Create pull request
      - name: Create Pull Request
        if: ${{ needs.EXPORT_PROPERTIES.outputs.changelog != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          BRANCH="changelog-update-$VERSION"

          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          git checkout -b $BRANCH
          git commit -asm "Changelog update - $VERSION"
          git push --set-upstream origin $BRANCH

          gh pr create \
            --title "Changelog update - \`$VERSION\`" \
            --body "Current pull request contains patched \`CHANGELOG.md\` file for the \`$VERSION\` version." \
            --base "${{ github.event.release.target_commitish }}" \
            --head $BRANCH \
            --label ignore-for-release
